### ISSUE TITLE
jenkins::job does not work when authentication is enabled

### ISSUE THREAD

**Issue by Xylakant** [jenkinsci/puppet-jenkins#259]
the auth parameter is ignored for jenkins::cli::cmd which is used by jenkins::job::present.

**Comment by v1v** [comment]
I don't know if this is related to. But I've got some issues too when I run the below configuration:
```
# -----------------------------------------------------------------------------
class jenkins_king::ess_jobs ()  {
  jenkins::job { 'ess_dolores':
    config => template('jenkins_king/ess_dolores-job.xml.erb'),
  }
}
```

```
root@jenkins-stockholm:~# puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for jenkins-stockholm.int.midasplayer.com
Info: Applying configuration version '1428922631'
Notice: /Stage[main]/Jenkins::Cli/Exec[jenkins-cli]/returns: executed successfully
Notice: /Stage[main]/Jenkins_king::Ess_jobs/Jenkins::Job[ess_dolores]/Jenkins::Job::Present[ess_dolores]/File[/tmp/ess_dolores-config.xml]/ensure: defined content as '{md5}5884756141886772b2d1aa91696fd404'
Error: cat /tmp/ess_dolores-config.xml | java -jar /usr/share/jenkins/jenkins-cli.jar -s http://localhost:8080 update-job ess_dolores returned 255 instead of one of [0]
Error: /Stage[main]/Jenkins_king::Ess_jobs/Jenkins::Job[ess_dolores]/Jenkins::Job::Present[ess_dolores]/Exec[jenkins update-job ess_dolores]/returns: change from notrun to 0 failed: cat /tmp/ess_dolores-config.xml | java -jar /usr/share/jenkins/jenkins-cli.jar -s http://localhost:8080 update-job ess_dolores returned 255 instead of one of [0]
Notice: /Stage[main]/Jenkins::Cli/Exec[reload-jenkins]: Dependency Exec[jenkins update-job ess_dolores] has failures: true
Warning: /Stage[main]/Jenkins::Cli/Exec[reload-jenkins]: Skipping because of failed dependencies
Notice: /Stage[main]/Jenkins_king::Ess_jobs/Jenkins::Job[ess_dolores]/Jenkins::Job::Present[ess_dolores]/Exec[jenkins enable-job ess_dolores]: Dependency Exec[jenkins update-job ess_dolores] has failures: true
Warning: /Stage[main]/Jenkins_king::Ess_jobs/Jenkins::Job[ess_dolores]/Jenkins::Job::Present[ess_dolores]/Exec[jenkins enable-job ess_dolores]: Skipping because of failed dependencies
Notice: Finished catalog run in 36.88 seconds
```

```
root@jenkins-stockholm:/var/lib/jenkins# cat /tmp/ess_dolores-config.xml | java -jar /usr/share/jenkins/jenkins-cli.jar -s http://localhost:8080 update-job ess_dolores
hudson.security.AccessDeniedException2: anonymous is missing the Job/Configure permission
	at hudson.security.ACL.checkPermission(ACL.java:55)
	at hudson.model.AbstractItem.checkPermission(AbstractItem.java:476)
	at hudson.model.AbstractItem.updateByXml(AbstractItem.java:619)
	at hudson.cli.UpdateJobCommand.run(UpdateJobCommand.java:47)
	at hudson.cli.CLICommand.main(CLICommand.java:234)
	at hudson.cli.CliManagerImpl.main(CliManagerImpl.java:92)
	at sun.reflect.GeneratedMethodAccessor385.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:309)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:290)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:249)
	at hudson.remoting.UserRequest.perform(UserRequest.java:118)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:328)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at hudson.cli.CliManagerImpl$1.call(CliManagerImpl.java:63)
	at hudson.remoting.InterceptingExecutorService$2.call(InterceptingExecutorService.java:95)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

I've already tried with two different approaches:
- Enable anonymous job generation. It works. But I cannot use that configuration at all. :(
- Using the ssh key file: https://github.com/jenkinsci/puppet-jenkins#cli-helper But it didn't work.

Let me know if you need further details.

Thanks.
