### ISSUE TITLE
Bug when it tries puppet-jenkins tries to create a user

### ISSUE THREAD

**Issue by Asher256** [jenkinsci/puppet-jenkins#476]
Hi,

A bug is happening when puppet-jenkins tried to create a user:
```
/usr/bin/java -jar /usr/share/jenkins/jenkins-cli.jar -s http://127.0.0.1:8181 groovy /usr/share/jenkins/puppet_helper.groovy create_or_update_user asher256 myemail@gmail.com 'asher' 'Asher' 'AAAAB3NzaC1yc2EAAAADAQABAAABAQC2GuAOQcUVa76N1j7wfgwZl4OZgzdO0RpsbX8aQ01unC3UmAJPkgYp4jCBBXg1m0DuWe9SieewCWiYdYT69u5jPUw3glIpxuU5MODWMewleGCcMCKcIEjhkTXNqVzYdMvEllMSBHCtH0FVbW+gljTSG3XH4HdvDbBqUat1j7AECXVVf10BnLZKM3gJUWC7znoaBS/lNaZZTedBLy5k1hx7juITw6i+TUEjYvFaBKQ7PDzbCYXwFDinNvcsmIT4nKydR7Rf+XaLZ0AIcny9Gs+mdnlPJYlFJG0UXzK3tKE7t0DzHVdlT6ommsgPlvXulvMjWVpDWOsFXPhWKlYJsJLT'
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
RemoteClass: 668: unable to resolve class FileCredentialsImpl 
 @ line 668, column 16.
           cred = new FileCredentialsImpl(
                  ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:302)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:861)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:550)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:499)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:302)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:281)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:731)
	at groovy.lang.GroovyShell.run(GroovyShell.java:516)
	at hudson.cli.GroovyCommand.run(GroovyCommand.java:94)
	at hudson.cli.CLICommand.main(CLICommand.java:237)
	at hudson.cli.CliManagerImpl.main(CliManagerImpl.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:608)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:583)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:542)
	at hudson.remoting.UserRequest.perform(UserRequest.java:120)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:326)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at hudson.cli.CliManagerImpl$1.call(CliManagerImpl.java:63)
	at hudson.remoting.CallableDecoratorAdapter.call(CallableDecoratorAdapter.java:18)
	at hudson.remoting.CallableDecoratorList$1.call(CallableDecoratorList.java:21)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

Thank you in advance !

Asher256

**Comment by jhoblitt** [comment]
Wow - that is surprising. What version of jenkins are you using?

**Comment by jhoblitt** [comment]
Could you try changing that line to: 
```
cred = new org.jenkinsci.plugins.plaincredentials.impl.FileCredentialsImpl(...
```
?

**Comment by Asher256** [comment]
I modified the puppet_helper.groovy and i got the same error message:
```
RemoteClass: 668: unable to resolve class org.jenkinsci.plugins.plaincredentials.impl.FileCredentialsImpl 
 @ line 668, column 16.
           cred = new org.jenkinsci.plugins.plaincredentials.impl.FileCredentialsImpl(
                  ^
```

Some informations:
My operating system is Debian Jessie.
Jenkins version: 1.625.3

**Comment by jhoblitt** [comment]
I've reverted #467 as it'll probably be a few days before I have the time to trouble shoot this.  @Asher256 Could you confirm that the current master works for you?

**Comment by Asher256** [comment]
Yes, it worked after the revert of #467 . Thank you JHoblitt!

Fell free to send me a message once you solve the bug caused by #467 . I would happy to check if the master branch works well.

**Comment by jhoblitt** [comment]
@Asher256 I'm going to close this issue (since it is essentially resolved) but I will ping you when the feature is put back in.  Thanks for reporting!
