### ISSUE TITLE
jenkins::credentials is not working with credentials plugin > version 1.24

### ISSUE THREAD

**Issue by ltutar** [jenkinsci/puppet-jenkins#601]
Hi,

I have the following yaml
```
jenkins::plugin_hash:
    'locale':
       version: "1.2"
       source: 'file:/tmp/jenkins_plugins/locale.hpi'
    'credentials':
       version: "1.24"
       source: 'file:/tmp/jenkins_plugins/credentials.hpi'
    'ssh-credentials':
       version: "1.12"
       source: 'file:/tmp/jenkins_plugins/ssh-credentials.hpi'
```
If I use any credentials above 1.24 like 1.25 or 2.07. See http://updates.jenkins-ci.org/download/plugins/credentials/

I get jenkins-cli error. When I google it, it may be related to ssh-credentials. I do not understand why I should stuck with credentials version 1.24 or what is missing?
```
Notice: /Stage[main]/Jenkins::Plugins/Jenkins::Plugin[credentials]/File[/var/lib/jenkins/plugins/credentials.hpi]/seltype: seltype changed 'user_tmp_t' to 'var_lib_t'
Info: Class[Jenkins::Plugins]: Scheduling refresh of Class[Jenkins::Service]
Info: Class[Jenkins::Service]: Scheduling refresh of Service[jenkins]
Notice: /Stage[main]/Jenkins::Service/Service[jenkins]: Triggered 'refresh' from 3 events
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: ERROR: Unexpected exception occurred while performing groovy command.
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: RemoteClass: 58: unable to resolve class SchemeRequirement 
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns:  @ line 58, column 9.
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns:            new SchemeRequirement("ssh")
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns:            ^
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: RemoteClass: 67: unable to resolve class Domain 
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns:  @ line 67, column 38.
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns:      def findCredentialsById(String id, Domain domain=Domain.global()) {
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns:                                         ^
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: RemoteClass: 370: unable to resolve class UsernamePasswordCredentialsImpl 
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns:  @ line 370, column 21.
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns:          credentials = new UsernamePasswordCredentialsImpl(
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns:                        ^
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: RemoteClass: 380: unable to resolve class BasicSSHUserPrivateKey.DirectEntryPrivateKeySource 
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns:  @ line 380, column 22.
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns:            key_source = new BasicSSHUserPrivateKey.DirectEntryPrivateKeySource(private_key)
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns:                         ^
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: RemoteClass: 382: unable to resolve class BasicSSHUserPrivateKey.FileOnMasterPrivateKeySource 
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns:  @ line 382, column 22.
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns:            key_source = new BasicSSHUserPrivateKey.FileOnMasterPrivateKeySource(private_key)
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns:                         ^
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: RemoteClass: 384: unable to resolve class BasicSSHUserPrivateKey 
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns:  @ line 384, column 21.
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns:          credentials = new BasicSSHUserPrivateKey(
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns:                        ^
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: RemoteClass: 557: unable to resolve class UsernamePasswordCredentialsImpl 
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns:  @ line 557, column 16.
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns:            cred = new UsernamePasswordCredentialsImpl(
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns:                   ^
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: RemoteClass: 567: unable to resolve class BasicSSHUserPrivateKey.DirectEntryPrivateKeySource 
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns:  @ line 567, column 19.
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns:            def key = new BasicSSHUserPrivateKey.DirectEntryPrivateKeySource(
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns:                      ^
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: RemoteClass: 570: unable to resolve class BasicSSHUserPrivateKey 
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns:  @ line 570, column 16.
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns:            cred = new BasicSSHUserPrivateKey(
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns:                   ^
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 9 errors
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:302)
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:861)
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:550)
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:499)
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:302)
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:281)
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:731)
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 	at groovy.lang.GroovyShell.run(GroovyShell.java:516)
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 	at hudson.cli.GroovyCommand.run(GroovyCommand.java:86)
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 	at hudson.cli.CLICommand.main(CLICommand.java:256)
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 	at hudson.cli.CliManagerImpl.main(CliManagerImpl.java:92)
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 	at java.lang.reflect.Method.invoke(Method.java:606)
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:608)
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:583)
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:542)
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 	at hudson.remoting.UserRequest.perform(UserRequest.java:120)
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 	at hudson.remoting.Request$2.run(Request.java:332)
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 	at hudson.cli.CliManagerImpl$1.call(CliManagerImpl.java:63)
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 	at hudson.remoting.CallableDecoratorAdapter.call(CallableDecoratorAdapter.java:18)
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 	at hudson.remoting.CallableDecoratorList$1.call(CallableDecoratorList.java:21)
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: 	at java.lang.Thread.run(Thread.java:745)
Error: /usr/bin/java -jar /usr/lib/jenkins/jenkins-cli.jar -s http://127.0.0.1:8080 groovy /usr/lib/jenkins/puppet_helper.groovy create_or_update_credentials tutti 'xebia1' '3ab58aaf-5692-420b-b889-c6c5f337cf0b' 'gitblit user tutti - managed by Puppet' '' returned 1 instead of one of [0]
Error: /Stage[main]/Jenkins_config::Config/Jenkins::Credentials[tutti]/Jenkins::Cli::Exec[create-jenkins-credentials-tutti]/Exec[create-jenkins-credentials-tutti]/returns: change from notrun to 0 failed: /usr/bin/java -jar /usr/lib/jenkins/jenkins-cli.jar -s http://127.0.0.1:8080 groovy /usr/lib/jenkins/puppet_helper.groovy create_or_update_credentials tutti 'xebia1' '3ab58aaf-5692-420b-b889-c6c5f337cf0b' 'gitblit user tutti - managed by Puppet' '' returned 1 instead of one of [0]
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Job[publish-petclinic-to-xldeploy-levent]/Jenkins::Job::Present[publish-petclinic-to-xldeploy-levent]/File[/tmp/publish-petclinic-to-xldeploy-levent-config.xml]: Dependency Exec[create-jenkins-credentials-tutti] has failures: true
Warning: /Stage[main]/Jenkins_config::Config/Jenkins::Job[publish-petclinic-to-xldeploy-levent]/Jenkins::Job::Present[publish-petclinic-to-xldeploy-levent]/File[/tmp/publish-petclinic-to-xldeploy-levent-config.xml]: Skipping because of failed dependencies
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Job[publish-petclinic-to-xldeploy-levent]/Jenkins::Job::Present[publish-petclinic-to-xldeploy-levent]/Exec[jenkins create-job publish-petclinic-to-xldeploy-levent]: Dependency Exec[create-jenkins-credentials-tutti] has failures: true
Warning: /Stage[main]/Jenkins_config::Config/Jenkins::Job[publish-petclinic-to-xldeploy-levent]/Jenkins::Job::Present[publish-petclinic-to-xldeploy-levent]/Exec[jenkins create-job publish-petclinic-to-xldeploy-levent]: Skipping because of failed dependencies
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Job[publish-petclinic-to-xldeploy-levent]/Jenkins::Job::Present[publish-petclinic-to-xldeploy-levent]/Exec[jenkins update-job publish-petclinic-to-xldeploy-levent]: Dependency Exec[create-jenkins-credentials-tutti] has failures: true
Warning: /Stage[main]/Jenkins_config::Config/Jenkins::Job[publish-petclinic-to-xldeploy-levent]/Jenkins::Job::Present[publish-petclinic-to-xldeploy-levent]/Exec[jenkins update-job publish-petclinic-to-xldeploy-levent]: Skipping because of failed dependencies
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Job[publish-petclinic-to-xldeploy-levent]/Jenkins::Job::Present[publish-petclinic-to-xldeploy-levent]/Exec[jenkins enable-job publish-petclinic-to-xldeploy-levent]: Dependency Exec[create-jenkins-credentials-tutti] has failures: true
Warning: /Stage[main]/Jenkins_config::Config/Jenkins::Job[publish-petclinic-to-xldeploy-levent]/Jenkins::Job::Present[publish-petclinic-to-xldeploy-levent]/Exec[jenkins enable-job publish-petclinic-to-xldeploy-levent]: Skipping because of failed dependencies
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Job[ECP30]/Jenkins::Job::Present[ECP30]/File[/tmp/ECP30-config.xml]: Dependency Exec[create-jenkins-credentials-tutti] has failures: true
Warning: /Stage[main]/Jenkins_config::Config/Jenkins::Job[ECP30]/Jenkins::Job::Present[ECP30]/File[/tmp/ECP30-config.xml]: Skipping because of failed dependencies
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Job[ECP30]/Jenkins::Job::Present[ECP30]/Exec[jenkins create-job ECP30]: Dependency Exec[create-jenkins-credentials-tutti] has failures: true
Warning: /Stage[main]/Jenkins_config::Config/Jenkins::Job[ECP30]/Jenkins::Job::Present[ECP30]/Exec[jenkins create-job ECP30]: Skipping because of failed dependencies
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Job[ECP30]/Jenkins::Job::Present[ECP30]/Exec[jenkins update-job ECP30]: Dependency Exec[create-jenkins-credentials-tutti] has failures: true
Warning: /Stage[main]/Jenkins_config::Config/Jenkins::Job[ECP30]/Jenkins::Job::Present[ECP30]/Exec[jenkins update-job ECP30]: Skipping because of failed dependencies
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Job[ECP30]/Jenkins::Job::Present[ECP30]/Exec[jenkins enable-job ECP30]: Dependency Exec[create-jenkins-credentials-tutti] has failures: true
Warning: /Stage[main]/Jenkins_config::Config/Jenkins::Job[ECP30]/Jenkins::Job::Present[ECP30]/Exec[jenkins enable-job ECP30]: Skipping because of failed dependencies
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Job[ECP21]/Jenkins::Job::Present[ECP21]/File[/tmp/ECP21-config.xml]: Dependency Exec[create-jenkins-credentials-tutti] has failures: true
Warning: /Stage[main]/Jenkins_config::Config/Jenkins::Job[ECP21]/Jenkins::Job::Present[ECP21]/File[/tmp/ECP21-config.xml]: Skipping because of failed dependencies
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Job[ECP21]/Jenkins::Job::Present[ECP21]/Exec[jenkins create-job ECP21]: Dependency Exec[create-jenkins-credentials-tutti] has failures: true
Warning: /Stage[main]/Jenkins_config::Config/Jenkins::Job[ECP21]/Jenkins::Job::Present[ECP21]/Exec[jenkins create-job ECP21]: Skipping because of failed dependencies
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Job[ECP21]/Jenkins::Job::Present[ECP21]/Exec[jenkins update-job ECP21]: Dependency Exec[create-jenkins-credentials-tutti] has failures: true
Warning: /Stage[main]/Jenkins_config::Config/Jenkins::Job[ECP21]/Jenkins::Job::Present[ECP21]/Exec[jenkins update-job ECP21]: Skipping because of failed dependencies
Notice: /Stage[main]/Jenkins::Cli::Reload/Exec[reload-jenkins]: Dependency Exec[create-jenkins-credentials-tutti] has failures: true
Warning: /Stage[main]/Jenkins::Cli::Reload/Exec[reload-jenkins]: Skipping because of failed dependencies
Notice: /Stage[main]/Jenkins_config::Config/Jenkins::Job[ECP21]/Jenkins::Job::Present[ECP21]/Exec[jenkins enable-job ECP21]: Dependency Exec[create-jenkins-credentials-tutti] has failures: true
Warning: /Stage[main]/Jenkins_config::Config/Jenkins::Job[ECP21]/Jenkins::Job::Present[ECP21]/Exec[jenkins enable-job ECP21]: Skipping because of failed dependencies
Notice: /Stage[main]/Jenkins/Anchor[jenkins::end]: Dependency Exec[create-jenkins-credentials-tutti] has failures: true
Warning: /Stage[main]/Jenkins/Anchor[jenkins::end]: Skipping because of failed dependencies
Info: Stage[main]: Unscheduling all events on Stage[main]
Notice: Applied catalog in 143.11 seconds
[root@jenkinsagent ~]# 
```

**Comment by elconas** [comment]
Could be extra dependency to icon-shim ?

https://github.com/jenkinsci/credentials-plugin/compare/credentials-1.24...credentials-1.25

**Comment by elconas** [comment]
Installing icon-shim solved the issue.

**Comment by ltutar** [comment]
It also solved my issue. I can now use version 2.0.7 of credentials. Thank you very much.
