### ISSUE TITLE
$::jenkins::libdir is undef in jenkins::cli class

### ISSUE THREAD

**Issue by bplunkert** [jenkinsci/puppet-jenkins#654]
When I apply my jenkins wrapper module in puppet, it seems there is an issue preventing the $::jenkins::libdir variable from being available in the jenkins::cli class.

I get these warnings and error message:

> Warning: Scope(Class[Jenkins::Cli]): Could not look up qualified variable '::jenkins::params::port'; class ::jenkins::params has not been evaluated
>        Warning: Scope(Class[Jenkins::Cli]): Could not look up qualified variable '::jenkins::params::prefix'; class ::jenkins::params has not been evaluated
>        Warning: Scope(Class[Jenkins::Cli_helper]): Could not look up qualified variable '::jenkins::params::port'; class ::jenkins::params has not been evaluated
>        Warning: Scope(Class[Jenkins::Cli_helper]): Could not look up qualified variable '::jenkins::params::prefix'; class ::jenkins::params has not been evaluated
>        . . .
>        [snip]
>         . . . 
>                Notice: /Stage[main]/Jenkins::Cli/Exec[jenkins-cli]/returns: java.io.FileNotFoundException: /jenkins.war (No such file or directory)
>        Notice: /Stage[main]/Jenkins::Cli/Exec[jenkins-cli]/returns:     at java.util.zip.ZipFile.open(Native Method)
>        Notice: /Stage[main]/Jenkins::Cli/Exec[jenkins-cli]/returns:     at java.util.zip.ZipFile.<init>(ZipFile.java:215)
>        Notice: /Stage[main]/Jenkins::Cli/Exec[jenkins-cli]/returns:     at java.util.zip.ZipFile.<init>(ZipFile.java:145)
>        Notice: /Stage[main]/Jenkins::Cli/Exec[jenkins-cli]/returns:     at java.util.zip.ZipFile.<init>(ZipFile.java:116)
>        Notice: /Stage[main]/Jenkins::Cli/Exec[jenkins-cli]/returns:     at sun.tools.jar.Main.extract(Main.java:947)
>        Notice: /Stage[main]/Jenkins::Cli/Exec[jenkins-cli]/returns:     at sun.tools.jar.Main.run(Main.java:258)
>        Notice: /Stage[main]/Jenkins::Cli/Exec[jenkins-cli]/returns:     at sun.tools.jar.Main.main(Main.java:1231)
>        Error: jar -xf /jenkins.war WEB-INF/jenkins-cli.jar && mv WEB-INF/jenkins-cli.jar /jenkins-cli.jar && rm -rf WEB-INF returned 1 instead of one of [0]
>        Error: /Stage[main]/Jenkins::Cli/Exec[jenkins-cli]/returns: change from notrun to 0 failed: jar -xf /jenkins.war WEB-INF/jenkins-cli.jar && mv WEB-INF/jenkins-cli.jar /jenkins-cli.jar && rm -rf WEB-INF returned 1 instead of one of [0]
>        Notice: /Stage[main]/Jenkins::Cli/File[/jenkins-cli.jar]: Dependency Exec[jenkins-cli] has failures: true

Note in particular the path `/jenkins.war` which seems to imply there is no value set for $jenkins::libdir. I am declaring the jenkins class as such:

```
    class { 'jenkins':
        configure_firewall => false,
        executors => 0,
        libdir => '/usr/lib/jenkins' # Set explicitly as a failed workaround attempt
    }
```

Since it seemed the error resulted from an undef value in $jenkins::libdir, I added the following to jenkins::cli:

```
validate_absolute_path($jenkins::libdir)
```

Sure enough, adding the above line triggered the expected failure of validate_absolute_path:

> ```
>    Error: Evaluation Error: Error while evaluating a Function Call, "" is not an absolute path. at /tmp/kitchen/modules/jenkins/manifests/cli.pp:25:3 on node jenkins-puppetlabs-centos-66-64-nocm.pulse.corp
> ```

I am testing on CentOS 6, running puppet 3.8.6 using the future parser mode. I am able to reproduce the issue using both release version 1.7.0 of this module as well as the latest master branch revision.

**Comment by bplunkert** [comment]
This issue went away for us on its own. I think it might be related to updates in the concat module.
