### ISSUE TITLE
slave password authentication broken

### ISSUE THREAD

**Issue by jhoblitt** [jenkinsci/puppet-jenkins#714]
@xdexter commented on #710 

After this commit i have error on my slaves:
```
jan 16, 2017 6:38:01 PM org.apache.commons.httpclient.HttpMethodDirector authenticateHost
ADVERTÊNCIA: Required credentials not available for BASIC @jenkins.camerite.local:80
jan 16, 2017 6:38:01 PM org.apache.commons.httpclient.HttpMethodDirector authenticateHost
ADVERTÊNCIA: Preemptive authentication requested but no default credentials available
jan 16, 2017 6:38:01 PM hudson.plugins.swarm.SwarmClient discoverFromMasterUrl
GRAVE: Failed to fetch slave info from Jenkins, HTTP response code: 403
jan 16, 2017 6:38:01 PM hudson.plugins.swarm.Client run
GRAVE: RetryException occurred
hudson.plugins.swarm.RetryException: Failed to fetch slave info from Jenkins, HTTP response code: 403
at hudson.plugins.swarm.SwarmClient.discoverFromMasterUrl(SwarmClient.java:231)
at hudson.plugins.swarm.Client.run(Client.java:116)
at hudson.plugins.swarm.Client.main(Client.java:88)
```

**Comment by jhoblitt** [comment]
The bug is caused by `runuser` using a login shell which does not inherit the `JENKINS_PASSWORD` env var.

**Comment by jhoblitt** [comment]
I just realized that #715 only "fixes" auth under systemd...
